set nocompatible
filetype off
call plug#begin()

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-easy-align', { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] } " ga<obj><target>
Plug 'junegunn/seoul256.vim'
Plug 'StanAngeloff/php.vim', { 'for': 'php' }
Plug 'othree/html5.vim', { 'for': 'html' }
Plug 'elzr/vim-json', { 'for': 'json' }
Plug 'alvan/vim-closetag', { 'for': ['html', 'php', 'xml']}
Plug 'cakebaker/scss-syntax.vim', { 'for': ['sass', 'scss', 'less', 'css']}
Plug 'hail2u/vim-css3-syntax', { 'for': ['sass', 'scss', 'less', 'css']}
Plug 'scrooloose/nerdcommenter'

call plug#end()
filetype plugin indent on

syntax on
colo seoul256
set bg=dark

set ai si is ic nu rnu ts=4 sw=4 et nowrap
set backspace=indent,eol,start
set encoding=utf-8 tenc=utf-8 fenc=utf-8
set laststatus=2
set nostartofline

" Plugin settings
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.xml"
let g:PHP_outdentphpescape = 0
let g:acp_enableAtStartup = 1

" Netrw settings
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

let mapleader=","

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
nmap Y y$
imap jj <Esc>
no <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
no <silent> <expr> k (v:count == 0 ? 'gk' : 'k')
nn <space> <c-w>
nn <leader>f :echo @%<cr>
nn <leader>ms :mks! .vimsession<cr>
nn <leader>ss :source .vimsession<cr>
nn <tab> :Buffers<cr>
nn <C-p> :Files<cr>
nn <leader>p :GFiles<cr>

" Insert mode movement
ino <C-k> <Up>
ino <C-j> <Down>
ino <C-h> <Left>
ino <C-l> <Right>

" FZF grep
command! -bang -nargs=* Find call fzf#vim#grep('grep -srnw '.shellescape(<q-args>), 1, <bang>0)

" Relative number switching
autocmd InsertEnter * :call DisableRelNo()
autocmd InsertLeave * :call EnableRelNo()

" Function to toggle between line numbers and relativenumbers
function! NumberToggle()
    if(&relativenumber == 1)
        call DisableRelNo()
    else
        call EnableRelNo()
    endif
endfunc

function! EnableRelNo()
    set number
    set relativenumber
endfunc

function! DisableRelNo()
    set number
    set norelativenumber
endfunc
